version: '3.8'

services:
  discord-bot:
    build: .
    container_name: gameling-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    # Discord bots don't need port exposure
    # ports:
    #   - "3000:3000"